version: '3.8'

services:
  mosajjil:
    build: .
    container_name: mosajjil
    ports:
      - "8080:3000"
    restart: unless-stopped
    volumes:
      - downloads:/app/downloads
    environment:
      - NODE_ENV=production
      - PORT=3000

volumes:
  downloads:
